### ISSUE TITLE
Detected memoryleak

### ISSUE THREAD

**Issue by pe1hmm** [pschatzmann/TinyFTPClient#6]
Great that TinyFTPClient is developped. 
Exactly what i can use, but when I included upload in my code, the ESP8266 crashed after a few hours. It looked like a memoryleak. 
This can be reproduced with a small addition to the upload example code, compiled with Arduino 1.8.19.
```

#include <ESP8266WiFi.h>
#include "ArduinoFTPClient.h"

WiFiClient cmd;
WiFiClient data;
FTPClient client(cmd, data);

unsigned long pm;

void upload() {
    client.begin(IPAddress(11,22,33,44), "ftpname", "ftppass");
    FTPFile file = client.open("/httpdocs/tmp/tst.txt", WRITE_MODE);
  /*
    char buffer[100];
    for (int j=0;j<100;j++){
        sprintf(buffer, "test %d", j);
        file.println(buffer);
    } */
    file.close(); 
    client.end();
}


void setup() {
    Serial.begin(115200);
    delay(1000);
    WiFi.begin("wifiname", "wifipass");
    while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
    }

    IPAddress localAddress = WiFi.localIP();
    Serial.println();
    Serial.print("Started with address ");
    Serial.println(localAddress.toString());

    //FTPLogger::setOutput(Serial);
    //FTPLogger::setLogLevel(LOG_DEBUG);
    Serial.println("GO");
    pm = millis();
} // setup()


void loop() {
  if ((millis()-pm) > 5000) {
    pm = millis();
    Serial.printf("Start FTP. FreeHeap=%d", ESP.getFreeHeap());
    upload();
    Serial.printf("  Upload ready. FreeHeap=%d\n", ESP.getFreeHeap()); 
  }
} // loop()`
```

Both with and without  file.println(buffer); the FreeHeap decreases :
09:54:41.840 -> GO
09:54:46.856 -> Start FTP. FreeHeap=49928  Upload ready. FreeHeap=49192
09:54:51.825 -> Start FTP. FreeHeap=49232  Upload ready. FreeHeap=48608
..
09:56:21.871 -> Start FTP. FreeHeap=47792  Upload ready. FreeHeap=47168
09:56:26.840 -> Start FTP. FreeHeap=47712  Upload ready. FreeHeap=47088

The line `FTPFile file = client.open("/httpdocs/tmp/tst.txt", WRITE_MODE);  `introduces this issue.
The file is created and updated as it should (when remarks removed).
Hope this can be reproduced, pinpointed and solved. Thanx. Wim

**Comment by pschatzmann** [comment]
I was indeed allocating a new object w/o feeing it. 
I committed a correction: can you double check ?

**Comment by pe1hmm** [comment]
Yes, i'll check now.
